MyOSBB/Controllers/AnnouncementsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyOSBB.DAL.Interfaces;
using MyOSBB.DAL.Models;

namespace MyOSBB.Controllers
{
    [Authorize(Roles = "Users")]
    public class AnnouncementsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        //private readonly ApplicationDbContext _context;
        private readonly IUnitOfWork _unitOfWork;

        public AnnouncementsController(UserManager<ApplicationUser> userManager, IUnitOfWork unitOfWork /*ApplicationDbContext context*/)
        {
            _userManager = userManager;
            //_context = context;
            _unitOfWork = unitOfWork;
        }

        // GET: Announcements
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _unitOfWork.Announcements.GetDbSet().Include(a => a.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Announcements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var announcement = await _unitOfWork.Announcements.GetDbSet()
                .Include(a => a.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (announcement == null)
            {
                return NotFound();
            }

            return View(announcement);
        }

        // GET: Announcements/Create
        public IActionResult Create()
        {
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            var user = _userManager.GetUserAsync(User).Result;
            ViewData["UserId"] = _unitOfWork.Users.GetDbSet().Where(r => r.Id == user.Id).FirstOrDefaultAsync().Result.Id;
            return View();
        }

        // POST: Announcements/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,Date,UserId")] Announcement announcement)
        {
            if (ModelState.IsValid)
            {
                //_unitOfWork.Announcements.GetDbSet().Add(announcement);
                _unitOfWork.Add(announcement);
                await _unitOfWork.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = announcement.UserId;
            return View(announcement);
        }

        // GET: Announcements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var announcement = await _unitOfWork.Announcements.GetDbSet().SingleOrDefaultAsync(m => m.Id == id);
            if (announcement == null)
            {
                return NotFound();
            }
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", announcement.UserId);
            ViewData["UserId"] = announcement.UserId;
            return View(announcement);
        }

        // POST: Announcements/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,Date,UserId")] Announcement announcement)
        {
            if (id != announcement.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.Update(announcement);
                    await _unitOfWork.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnnouncementExists(announcement.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", announcement.UserId);
            ViewData["UserId"] = announcement.UserId;
            return View(announcement);
        }

        // GET: Announcements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var announcement = await _unitOfWork.Announcements.GetDbSet()
                .Include(a => a.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (announcement == null)
            {
                return NotFound();
            }

            return View(announcement);
        }

        // POST: Announcements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var announcement = await _unitOfWork.Announcements.GetDbSet().SingleOrDefaultAsync(m => m.Id == id);
            _unitOfWork.Remove(announcement);
            await _unitOfWork.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnnouncementExists(int id)
        {
            return _unitOfWork.Announcements.GetDbSet().Any(e => e.Id == id);
        }
    }
}

MyOSBB/Controllers/ContributionsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyOSBB.DAL.Data;
using MyOSBB.DAL.Interfaces;
using MyOSBB.DAL.Models;

namespace MyOSBB.Controllers
{
    [Authorize(Roles = "Users")]
    public class ContributionsController : Controller
    {        
        private readonly UserManager<ApplicationUser> _userManager;
        //private readonly ApplicationDbContext _context;
        private readonly IUnitOfWork _unitOfWork;

        public ContributionsController(UserManager<ApplicationUser> userManager, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;
            //_context = context;
            _unitOfWork = unitOfWork;
        }

        // GET: Contributions
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _unitOfWork.Contributions.GetDbSet().Include(c => c.Month).Include(c => c.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Contributions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contribution = await _unitOfWork.Contributions.GetDbSet()
                .Include(c => c.Month)
                .Include(c => c.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (contribution == null)
            {
                return NotFound();
            }

            return View(contribution);
        }

        // GET: Contributions/Create
        public IActionResult Create()
        {
            ViewData["MonthId"] = new SelectList(_unitOfWork.Months.GetDbSet(), "Id", "Name");
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");

            var user = _userManager.GetUserAsync(User).Result;
            ViewData["UserId"] = _unitOfWork.Users.GetDbSet().Where(r => r.Id == user.Id).FirstOrDefaultAsync().Result.Id;
            return View();
        }

        // POST: Contributions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Payment,PaymentDate,UserId,MonthId")] Contribution contribution)
        {
            if (ModelState.IsValid)
            {
                //_unitOfWork.Contributions.GetDbSet().Add(contribution);
                _unitOfWork.Contributions.Insert(contribution);
                await _unitOfWork.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MonthId"] = new SelectList(_unitOfWork.Months.GetDbSet(), "Id", "Name", contribution.MonthId);
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", contribution.UserId);
            ViewData["UserId"] = contribution.UserId;
            return View(contribution);
        }

        // GET: Contributions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contribution = await _unitOfWork.Contributions.GetDbSet().SingleOrDefaultAsync(m => m.Id == id);
            if (contribution == null)
            {
                return NotFound();
            }
            ViewData["MonthId"] = new SelectList(_unitOfWork.Months.GetDbSet(), "Id", "Name", contribution.MonthId);
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", contribution.UserId);
            ViewData["UserId"] = contribution.UserId;
            return View(contribution);
        }

        // POST: Contributions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Payment,PaymentDate,UserId,MonthId")] Contribution contribution)
        {
            if (id != contribution.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.Update(contribution);
                    await _unitOfWork.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContributionExists(contribution.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MonthId"] = new SelectList(_unitOfWork.Months.GetDbSet(), "Id", "Name", contribution.MonthId);
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", contribution.UserId);
            ViewData["UserId"] = contribution.UserId;
            return View(contribution);
        }

        // GET: Contributions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contribution = await _unitOfWork.Contributions.GetDbSet()
                .Include(c => c.Month)
                .Include(c => c.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (contribution == null)
            {
                return NotFound();
            }

            return View(contribution);
        }

        // POST: Contributions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contribution = await _unitOfWork.Contributions.GetDbSet().SingleOrDefaultAsync(m => m.Id == id);
            _unitOfWork.Contributions.GetDbSet().Remove(contribution);
            await _unitOfWork.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContributionExists(int id)
        {
            return _unitOfWork.Contributions.GetDbSet().Any(e => e.Id == id);
        }
    }
}

MyOSBB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MyOSBB.DAL.Data;
using MyOSBB.DAL.Models;

namespace MyOSBB.Controllers
{
    public class HomeController : Controller
    {
        private IServiceProvider _serviceProvider;
        private IConfiguration _configuration;
        public HomeController(IServiceProvider serviceProvider, IConfiguration configuration)
        {
            _serviceProvider = serviceProvider;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Admin()
        {
            ApplicationDbContext.CreateAdminAccount(_serviceProvider, _configuration).Wait();
            return View("Index");
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyOSBB/Controllers/UserDataController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyOSBB.Controllers
{
    public class UserDataController : Controller
    {
        // Use JavaScript for display all invoices in one page
        public IActionResult Index()
        {
            return View();
        }
    }
}

MyOSBB/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About OSBB";
}

<div class="row">
    <div class="col-md-3">
        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="~/images/MyOSBB_1.png" alt="ASP.NET" class="img-responsive" />
                </div>
                <div class="item">
                    <img src="~/images/MyOSBB_2.png" alt="Visual Studio" class="img-responsive" />
                </div>
                <div class="item">
                    <img src="~/images/MyOSBB_3.png" alt="Package Management" class="img-responsive" />
                </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="col-md-9">
        <h2>@ViewData["Title"]</h2>
    </div>
</div>

MyOSBB/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact OSBB";
}

<div class="row">
    <div class="col-md-3">
        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="~/images/MyOSBB_1.png" alt="ASP.NET" class="img-responsive" />
                </div>
                <div class="item">
                    <img src="~/images/MyOSBB_2.png" alt="Visual Studio" class="img-responsive" />
                </div>
                <div class="item">
                    <img src="~/images/MyOSBB_3.png" alt="Package Management" class="img-responsive" />
                </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="col-md-9">
        <h2>@ViewData["Title"]</h2>

        <address>
            Some were<br />
            top secret<br />
            <abbr title="Phone">P:</abbr>
            911
        </address>

        <address>
            <strong>Support:</strong> <a href="mailto:admin@vysoft.top">admin@vysoft.top</a><br />
            <strong>Admin:</strong> <a href="mailto:admin@vysoft.top">admin@vysoft.top</a>
        </address>
    </div>
</div>

MyOSBB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<div class="row">
    <div class="col-md-3">
        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="~/images/MyOSBB_1.png" alt="ASP.NET" class="img-responsive" />
                </div>
                <div class="item">
                    <img src="~/images/MyOSBB_2.png" alt="Visual Studio" class="img-responsive" />
                </div>
                <div class="item">
                    <img src="~/images/MyOSBB_3.png" alt="Package Management" class="img-responsive" />
                </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="col-md-9">
        @if (SignInManager.IsSignedIn(User))
        {
            <div class="col-md-9">
                <h2>Welcome @UserManager.GetUserName(User) to OSBB site.</h2>
                <h4>
                    As the member of OSBB you can get access to your personal information and common information of OSBB.<br />
                </h4>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <h4>You can look at your invoices on the <a asp-area="" asp-controller="UserData" asp-action="Index">User data</a> page and make your <a asp-area="" asp-controller="Contributions" asp-action="Index">contributions</a> to OSBB </h4>
                </div>
                <div class="col-md-4">
                    <h4>Also you can edit your profile on the <a asp-area="" asp-controller="Manage" asp-action="Index">manage account</a> page and make <a asp-area="" asp-controller="Announcements" asp-action="Index">announcements</a></h4>
                </div>
                @if (User.IsInRole("Admins"))
                {
                    <div class="col-md-4">
                        <h4>As the admin you additionaly have access to all users data.</h4>
                    </div>
                }
                else
                {
                    <div class="col-md-4">
                        <h4>As the user you see and get information only for you and your flat.</h4>
                    </div>
                }
            </div>
        }
        else
        {
            <div class="col-md-9">
                <h2>Welcome to OSBB site.</h2>
                <h4>
                    As the guest you can see only public information on the site.<br />
                    It is this page, page of public information about OSBB and contact page.
                </h4>
                <h4>To be a member of OSBB you need to live in our house. If you live in our house you can <a asp-area="" asp-controller="Account" asp-action="Register">register</a> as the user and after confirmation by admin you can <a asp-area="" asp-controller="Account" asp-action="Login">log in</a> as the user and get more functinalities of this site. </h4>
            </div>
        }
    </div>
</div>